fail if no json file found

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -35,7 +35,7 @@ runs:
 
     - name: auditor
       run: |
-        export JSON_DIFF=$(cat tmp/git-diff-actions/outputs/diff.json)
+        export JSON_DIFF=$(cat tmp/git-diff-actions/outputs/diff.json || echo "could not load diff.json" && exit 1)
         node src/main.js
       env:
         CONFIG: ${{ inputs.config }}
